#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List

import numpy as np
import pandas as pd

if not hasattr(np, "bool8"):
    np.bool8 = np.bool_
if not hasattr(np, "unicode_"):
    np.unicode_ = np.str_
if not hasattr(np, "bytes_"):
    np.bytes_ = np.bytes_

import plotly.express as px
from dash import Dash, Input, Output, dcc, html

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_RESULTS = SCRIPT_DIR / "output" / "cluster_results.json"

def parse_args():
    parser = argparse.ArgumentParser(description="Visualize clustered traces with Dash.")
    parser.add_argument(
        "--results",
        default=str(DEFAULT_RESULTS),
        help="Path to cluster_results.json generated by cluster_scripts.py.",
    )
    parser.add_argument("--host", default="0.0.0.0", help="Dash server host.")
    parser.add_argument("--port", type=int, default=8050, help="Dash server port.")
    parser.add_argument("--debug", action="store_true", help="Enable Dash debug mode.")
    return parser.parse_args()

def load_results(path):
    if not path.exists():
        raise FileNotFoundError(f"Results file {path} does not exist.")
    with path.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, list):
        raise ValueError("Results file is not a list.")
    return data

def build_dataframe(results):
    rows = []
    for entry in results:
        tsne = entry.get("tsne") or {}
        cluster_label = entry.get("cluster_label")
        cluster_label_str = str(cluster_label)
        rows.append(
            {
                "trace_id": entry.get("trace_id"),
                "domain": entry.get("domain"),
                "diff_hash": entry.get("diff_hash"),
                "script_id": entry.get("script_id"),
                "cluster_label": cluster_label_str,
                "cluster_score": entry.get("cluster_score"),
                "source_url": entry.get("source_url"),
                "page_url": entry.get("page_url"),
                "token_count": len(entry.get("tokens") or []),
                "tsne_x": tsne.get("x", 0.0),
                "tsne_y": tsne.get("y", 0.0),
                "tsne_z": tsne.get("z", 0.0),
            }
        )
    return pd.DataFrame(rows)

def sort_cluster_labels(labels):
    def sort_key(label):
        try:
            return (0, int(label))
        except ValueError:
            return (1, label)

    return sorted(labels, key=sort_key)

def launch_app(df: pd.DataFrame, raw_results, host, port, debug):
    if df.empty:
        raise ValueError("Dataframe is empty; run cluster_scripts.py first.")

    app = Dash(__name__)
    entry_lookup = {entry["trace_id"]: entry for entry in raw_results}

    cluster_order = sort_cluster_labels(df["cluster_label"].unique().tolist())
    palette = px.colors.qualitative.Plotly + px.colors.qualitative.Safe + px.colors.qualitative.Vivid
    color_map = {label: palette[idx % len(palette)] for idx, label in enumerate(cluster_order)}
    cluster_sizes = df["cluster_label"].value_counts().to_dict()
    fig = px.scatter_3d(
        df,
        x="tsne_x",
        y="tsne_y",
        z="tsne_z",
        color="cluster_label",
        color_discrete_map=color_map,
        category_orders={"cluster_label": cluster_order},
        hover_name="trace_id",
        hover_data={
            "domain": True,
            "source_url": True,
            "cluster_score": ":.2f",
            "token_count": True,
        },
        custom_data=["trace_id"],
    )
    fig.update_traces(marker=dict(size=6, opacity=0.85, showscale=False))
    fig.update_layout(
        margin=dict(l=0, r=160, t=40, b=0),
        legend=dict(
            title="Clusters",
            orientation="v",
            yanchor="top",
            y=1,
            xanchor="left",
            x=1.02,
            bgcolor="rgba(255,255,255,0.85)",
            bordercolor="rgba(0,0,0,0.2)",
            borderwidth=1,
            itemsizing="constant",
            font=dict(size=11),
        ),
        uirevision="cluster-view",
    )

    app.layout = html.Div(
        [
            html.Div([html.H2("Script Trace Clusters")]),
            html.Div(
                [
                    html.Div(
                        dcc.Graph(id="cluster-graph", figure=fig, style={"height": "70vh"}),
                        style={"flex": "0 0 70%"},
                    ),
                    html.Div(
                        [
                            html.H3("Cluster Summary"),
                            html.Pre(id="cluster-summary", children="Select a cluster or point to view stats."),
                            html.H3("Trace Details"),
                            html.Pre(id="trace-details", children="Click a point to load details."),
                        ],
                        style={
                            "flex": "1 1 30%",
                            "display": "flex",
                            "flexDirection": "column",
                            "gap": "1rem",
                        },
                    ),
                ],
                style={"display": "flex", "gap": "1rem", "alignItems": "stretch"},
            ),
        ],
        style={"fontFamily": "monospace", "padding": "1rem"},
    )

    @app.callback(
        [Output("trace-details", "children"), Output("cluster-summary", "children")],
        Input("cluster-graph", "clickData"),
    )
    def display_trace_details(click_data):
        if not click_data or "points" not in click_data:
            return (
                "Click a point to load details.",
                "Select a cluster or point to view stats.",
            )
        trace_id = click_data["points"][0]["customdata"][0]
        entry = entry_lookup.get(trace_id)
        if not entry:
            return (f"Trace {trace_id} not found.", "Select a cluster or point to view stats.")
        trimmed_tokens = entry.get("tokens", [])[:40]
        payload = {
            "trace_id": entry.get("trace_id"),
            "domain": entry.get("domain"),
            "diff_hash": entry.get("diff_hash"),
            "script_id": entry.get("script_id"),
            "cluster_label": entry.get("cluster_label"),
            "cluster_score": round(entry.get("cluster_score", 0.0), 3),
            "source_url": entry.get("source_url"),
            "page_url": entry.get("page_url"),
            "token_count": len(entry.get("tokens") or []),
            "tokens_preview": trimmed_tokens,
        }
        if len(entry.get("tokens", [])) > len(trimmed_tokens):
            payload["tokens_preview"].append("... (truncated)")
        cluster_label = entry.get("cluster_label")
        cluster_key = str(cluster_label)
        cluster_count = cluster_sizes.get(cluster_key, 0)
        cluster_summary = (
            f"Cluster {cluster_key}\n"
            f"Data points: {cluster_count}\n"
            f"Example trace: {entry.get('trace_id')}\n"
            f"Source URL: {entry.get('source_url') or 'n/a'}"
        )
        return json.dumps(payload, indent=2), cluster_summary

    app.run(host=host, port=port, debug=debug, use_reloader=False)

def main():
    args = parse_args()
    results = load_results(Path(args.results))
    df = build_dataframe(results)
    launch_app(df, results, host=args.host, port=args.port, debug=args.debug)

if __name__ == "__main__":
    main()
